version: '3'
services:
  lb:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app_network

  was1:
    image: openjdk:17-jdk-alpine
    container_name: spring-boot-app-1
    volumes:
      - ./your-local-project:/app 
    working_dir: /app  
    command: ["java", "-jar", "your-spring-boot-app.jar"]  
    environment:
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - app_network
    ports:
      - "8080:8080" 

  was2:
    image: openjdk:17-jdk-alpine
    container_name: spring-boot-app-2
    volumes:
      - ./your-local-project:/app
    working_dir: /app
    command: ["java", "-jar", "your-spring-boot-app.jar"]
    environment:
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - app_network
    ports:
      - "8081:8080" 

  mongodb:
    image: mongo:latest
    networks:
      - app_network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - app_network

  redis:
    image: redis:latest
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
